const express=require("express")
const app=express()
const dotenv=require("dotenv")
const cors=require("cors")
const connection=require("./config/connection")
const users=require("./routes/Userroute")
connection()
app.use(cors())
dotenv.config()
app.use(express.json())
app.use("/eshop/users",users)
app.listen(process.env.PORT,()=>{
    console.log("server is running at ",process.env.PORT)
})